export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_FAILED_MESSAGE = "LOGIN_FAILED_MESSAGE";
export const LOGIN_SUCCESS_REDIRECT = "LOGIN_SUCCESS_REDIRECT";

// / logout
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_SUCCESS_REDIRECT = "LOGOUT_SUCCESS_REDIRECT";

//me
export const USER_ME_REQUEST = "USER_ME_REQUEST";
export const USER_ME_SUCCESS = "USER_ME_SUCCESS";
export const USER_ME_FAILED = "USER_ME_FAILED";

//ORDER
export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILED = "ORDER_FAILED";

// category bank
export const FETCH_CATEGORY_SERVICE_REQUEST = "FETCH_CATEGORY_SERVICE_REQUEST";
export const FETCH_CATEGORY_SERVICE_SUCCESS = "FETCH_CATEGORY_SERVICE_SUCCESS";
export const FETCH_CATEGORY_SERVICE_FAILED = "FETCH_CATEGORY_SERVICE_FAILED";

export const FETCH_CATEGORY_STATUS_REQUEST = "FETCH_CATEGORY_STATUS_REQUEST";
export const FETCH_CATEGORY_STATUS_SUCCESS = "FETCH_CATEGORY_STATUS_SUCCESS";
export const FETCH_CATEGORY_STATUS_FAILED = "FETCH_CATEGORY_STATUS_FAILED";

export const FETCH_MITRA_REQUEST = "FETCH_MITRA_REQUEST";
export const FETCH_MITRA_SUCCESS = "FETCH_MITRA_SUCCESS";
export const FETCH_MITRA_FAILED = "FETCH_MITRA_FAILED";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_FAILURE = "GET_ORDER_BY_ID_FAILURE";

// src/redux/constants/orderConstants.js
export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAILURE = "UPDATE_ORDER_FAILURE";

//ORDER
export const EVIDEN_REQUEST = "EVIDEN_REQUEST";
export const EVIDEN_SUCCESS = "EVIDEN_SUCCESS";
export const EVIDEN_FAILED = "EVIDEN_FAILED";

export const FETCH_STATUS_EVIDEN_REQUEST = "FETCH_STATUS_EVIDEN_REQUEST";
export const FETCH_STATUS_EVIDEN_SUCCESS = "FETCH_STATUS_EVIDEN_SUCCESS";
export const FETCH_STATUS_EVIDEN_FAILED = "FETCH_STATUS_EVIDEN_FAILED";

export const CREATE_EVIDEN_REQUEST = "CREATE_EVIDEN_REQUEST";
export const CREATE_EVIDEN_SUCCESS = "CREATE_EVIDEN_SUCCESS";
export const CREATE_EVIDEN_FAILURE = "CREATE_EVIDEN_FAILURE";

//register
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS_REDIRECT = "REGISTER_SUCCESS_REDIRECT";
export const RESET_REGISTER_SUCCESS_REDIRECT =
   "RESET_REGISTER_SUCCESS_REDIRECT";

// DLETE ORDER
export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILED = "DELETE_ORDER_FAILED";

// DLETE ORDER
export const DELETE_EVIDENCE_REQUEST = "DELETE_EVIDENCE_REQUEST";
export const DELETE_EVIDENCE_SUCCESS = "DELETE_EVIDENCE_SUCCESS";
export const DELETE_EVIDENCE_FAILED = "DELETE_EVIDENCE_FAILED";


export const GET_EVIDENCE_BY_ID_REQUEST = "GET_EVIDENCE_BY_ID_REQUEST";
export const GET_EVIDENCE_BY_ID_SUCCESS = "GET_EVIDENCE_BY_ID_SUCCESS";
export const GET_EVIDENCE_BY_ID_FAILURE = "GET_EVIDENCE_BY_ID_FAILURE";

// src/redux/constants/orderConstants.js
export const UPDATE_EVIDENCE_REQUEST = "UPDATE_EVIDENCE_REQUEST";
export const UPDATE_EVIDENCE_SUCCESS = "UPDATE_EVIDENCE_SUCCESS";
export const UPDATE_EVIDENCE_FAILURE = "UPDATE_EVIDENCE_FAILURE";
